# Containers needed to test all backend services locally
version: '3.7'

services:
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - '80:80'

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -inMemory'
    environment:
      AWS_ACCESS_KEY_ID: 'placeholder'
      AWS_SECRET_ACCESS_KEY: 'placeholder'
    working_dir: '/home/dynamodblocal'

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: 'requests_cache_pytest'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: hunter2
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/data/db'

  redis:
    container_name: redis
    image: docker.io/bitnami/redis
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  mongodb_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
